version: "3.9"

services:
  redis:
    image: redis:alpine3.16
    ports:
      - "6379:6379"
    networks:
      - backend

  api:
    build:
      context: .
      target: prod
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    networks:
      - backend
    env_file:
      - .env

  sync:
    build:
      context: .
      target: sync
    volumes:
      - ./:/app
    networks:
      - backend
    env_file:
      - .env

networks:
  backend:
