name: New tag CI

on:
  push:
    tags: ["*"]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: equilibrefinance/api:latest,equilibrefinance/api:${{ github.ref_name }}
          target: prod
      
      - name: Build and push sync
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: equilibrefinance/sync:latest,equilibrefinance/sync:${{ github.ref_name }}
          target: sync

  tests:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: |
         docker run --rm --env-file=env.example -w /app --entrypoint sh equilibrefinance/api:${{ github.ref_name }} -c 'pip install coverage flake8 && flake8 && coverage run $(which api-test) && coverage report'
